'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.296
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WILLIAM_DonkeyKong.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property BobbDancing() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BobbDancing", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BobbDancing2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BobbDancing2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BobbGettingBarrel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BobbGettingBarrel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BobbHoldingBarrel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BobbHoldingBarrel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BobbRollingBarrel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BobbRollingBarrel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BobbSmiling() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BobbSmiling", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BobbStanding() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BobbStanding", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Coin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Coin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property coinv2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("coinv2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property explode1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("explode1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property explode2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("explode2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property explode3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("explode3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property hammerLeftSmasher1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hammerLeftSmasher1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property hammerLeftSmasher2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hammerLeftSmasher2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property hammerRightSmasher1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hammerRightSmasher1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property hammerRightSmasher2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hammerRightSmasher2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property help() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("help", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ladder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ladder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ladyInDistress() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ladyInDistress", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property level1_background() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("level1-background", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property lives() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lives", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property luigiClimb1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("luigiClimb1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property luigiClimb2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("luigiClimb2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property luigiClimb3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("luigiClimb3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property LuigiClimbTop1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LuigiClimbTop1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property luigiLeftFloat() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("luigiLeftFloat", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property luigiLeftMove1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("luigiLeftMove1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property luigiLeftMove2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("luigiLeftMove2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property luigiLeftMove3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("luigiLeftMove3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property luigiRightFloat() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("luigiRightFloat", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property luigiRightMove1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("luigiRightMove1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property luigiRightMove2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("luigiRightMove2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property luigiRightMove3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("luigiRightMove3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property marioClimb1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("marioClimb1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property marioClimb2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("marioClimb2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property marioClimb3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("marioClimb3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property MarioClimbTop1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MarioClimbTop1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property marioDead() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("marioDead", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property marioLeftFloat() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("marioLeftFloat", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property marioLeftMove1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("marioLeftMove1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property marioLeftMove2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("marioLeftMove2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property marioLeftMove3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("marioLeftMove3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property marioLeftSmash1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("marioLeftSmash1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property marioLeftSmash2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("marioLeftSmash2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property marioLeftSmasher1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("marioLeftSmasher1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property marioLeftSmasher2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("marioLeftSmasher2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property marioRightFloat() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("marioRightFloat", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property marioRightMove1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("marioRightMove1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property marioRightMove2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("marioRightMove2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property marioRightMove3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("marioRightMove3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property marioRightSmasher1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("marioRightSmasher1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property marioRightSmasher2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("marioRightSmasher2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property marioSpin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("marioSpin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PIKACHU() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PIKACHU", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
